version: '2'
services:
  rbac-management-studio:
    image: lerwys/docker-rbac-management-studio-wildfly
    ports:
      - "8082:8080"
      - "9992:9990"
      - "8445:8443"
    container_name: rbac-management-studio
    depends_on:
      - rbac-management-studio-postgres
    entrypoint: /wait-for-it.sh
    command: rbac-management-studio-postgres:5432 -- /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
    networks:
      - postgres-rbac

  rbac-management-studio-postgres:
    image: lerwys/docker-rbac-management-studio-postgres
    ports:
      - "5434:5432"
    container_name: rbac-management-studio-postgres
    volumes:
      - rbac-management-studio-postgres-volume:/var/lib/postgresql/data
    networks:
      - postgres-rbac
    env_file: env-vars/naming-service-postgres-vars.env

volumes:
  rbac-management-studio-postgres-volume:
    driver: local

networks:
  postgres-rbac:
    external:
      name: dockerrbacauthservicescomposed_postgres-rbac
