version: '2'
services:
  rbac-management-studio:
    image: lerwys/docker-rbac-management-studio-wildfly
    ports:
      - "8081:8080"
      - "9991:9990"
      - "8444:8443"
    depends_on:
      - rbac-management-studio-postgres
    networks:
      - postgres-rbac

  rbac-management-studio-postgres:
    image: lerwys/docker-rbac-management-studio-postgres
    ports:
      - "5433:5432"
    volumes:
      - rbac-management-studio-postgres-volume:/var/lib/postgresql/data
    networks:
      - postgres-rbac
    env_file: env-vars/naming-service-postgres-vars.env

volumes:
  rbac-management-studio-postgres-volume:
    driver: local

networks:
  postgres-rbac:
    external:
      name: dockerrbacauthservicescomposed_postgres-rbac
